import { StyleSheet } from 'react-native';
import { typographyScale } from '@/src/theme';
import { getSettingsFlowTokens, RADIUS, PAD, GAP, CONTENT_W } from '@/src/theme/settingsFlowTokens';
import { RADIUS_BUTTON } from '@/src/features/login/loginConstants';

export type LoginToken = ReturnType<typeof getSettingsFlowTokens>;

export type LoginStyles = ReturnType<typeof makeLoginStyles>;

type FlowShadow = {
  shadowColor: string;
  shadowOffset: { width: number; height: number };
  shadowOpacity: number;
  shadowRadius: number;
  elevation: number;
};

export function makeLoginStyles(TOKEN: LoginToken, SHADOW: FlowShadow, _resolvedMode: 'light' | 'dark') {
  return StyleSheet.create({
    container: { flex: 1 },
    flex: { flex: 1 },
    scrollContent: { paddingBottom: 40, paddingHorizontal: PAD, alignItems: 'center' },
    center: { justifyContent: 'center', alignItems: 'center' },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: PAD,
      paddingVertical: 12,
    },
    backBtn: { padding: 8 },
    title: { ...typographyScale.header, color: TOKEN.ink },
    headerRight: { width: 40 },
    body: { flex: 1, paddingTop: 24, width: CONTENT_W, maxWidth: '100%' },
    authErrorBlock: {
      alignItems: 'center',
      marginBottom: 16,
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: TOKEN.dangerSoft,
      borderRadius: RADIUS_BUTTON,
    },
    authErrorText: {
      ...typographyScale.bodySmall,
      color: TOKEN.danger,
      marginBottom: 8,
      textAlign: 'center' as const,
    },
    authErrorRetry: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: RADIUS_BUTTON,
      backgroundColor: TOKEN.danger,
    },
    authErrorRetryText: { ...typographyScale.button, color: '#FFF' },
    subtitle: { ...typographyScale.bodySmall, color: TOKEN.inkMuted, marginBottom: 24 },
    hint: { ...typographyScale.body, color: TOKEN.inkMuted, textAlign: 'center' },
    socialBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: RADIUS_BUTTON,
      marginBottom: 12,
    },
    appleBtn: { backgroundColor: '#000' },
    googleBtn: { backgroundColor: TOKEN.surface, borderWidth: 1, borderColor: TOKEN.border },
    socialBtnText: { ...typographyScale.button, color: '#FFF' },
    googleBtnText: { color: TOKEN.ink },
    dividerWrap: { flexDirection: 'row', alignItems: 'center', marginVertical: 20 },
    dividerLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: TOKEN.border },
    dividerText: { marginHorizontal: 12, ...typographyScale.caption, color: TOKEN.inkMuted },
    emailForm: { marginTop: 4 },
    inputLabel: { ...typographyScale.bodySmall, fontWeight: '600', color: TOKEN.ink, marginBottom: 6 },
    input: {
      backgroundColor: TOKEN.surface,
      borderWidth: 1,
      borderColor: TOKEN.border,
      borderRadius: RADIUS_BUTTON,
      paddingHorizontal: 14,
      paddingVertical: 12,
      ...typographyScale.body,
      color: TOKEN.ink,
    },
    passwordInputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: TOKEN.surface,
      borderWidth: 1,
      borderColor: TOKEN.border,
      borderRadius: RADIUS_BUTTON,
      paddingRight: 4,
    },
    passwordInput: {
      flex: 1,
      paddingHorizontal: 14,
      paddingVertical: 12,
      ...typographyScale.body,
      color: TOKEN.ink,
    },
    passwordEyeBtn: {
      padding: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emailSubmitBtn: {
      marginTop: 16,
      paddingVertical: 14,
      borderRadius: RADIUS_BUTTON,
      backgroundColor: TOKEN.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    toggleWrap: { marginTop: 16, alignItems: 'center' },
    toggleText: { ...typographyScale.bodySmall, color: TOKEN.accent, fontWeight: '600' },
    heroCard: {
      backgroundColor: TOKEN.surface,
      borderRadius: RADIUS.card,
      padding: PAD,
      borderWidth: 1,
      borderColor: TOKEN.border,
      ...SHADOW,
      marginBottom: GAP,
    },
    userRow: { flexDirection: 'row', alignItems: 'center' },
    avatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: TOKEN.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    userInfo: { flex: 1, minWidth: 0 },
    displayName: { ...typographyScale.bodyLarge, fontWeight: '700', color: TOKEN.ink },
    studyLevelLabel: { ...typographyScale.bodySmall, color: TOKEN.accent, marginTop: 4 },
    profileMeta: { ...typographyScale.bodySmall, color: TOKEN.accent, marginTop: 4 },
    emailMuted: { ...typographyScale.caption, color: TOKEN.inkMuted, marginTop: 2 },
    sectionBlock: { marginBottom: GAP },
    sectionHead: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    sectionAccent: { width: 3, height: 20, borderRadius: 4, backgroundColor: TOKEN.accent, marginRight: 10 },
    sectionAccentDanger: { backgroundColor: TOKEN.danger },
    sectionTitle: { ...typographyScale.section, color: TOKEN.ink, flex: 1 },
    listCard: {
      backgroundColor: TOKEN.surface,
      borderRadius: RADIUS.card,
      borderWidth: 1,
      borderColor: TOKEN.border,
      ...SHADOW,
    },
    listCardInner: { borderRadius: RADIUS.card, overflow: 'hidden' },
    listRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: PAD,
      minHeight: 52,
    },
    listRowPressable: {},
    listRowPressed: { opacity: 0.9 },
    listRowMain: { flex: 1, minWidth: 0 },
    listRowHorizontal: {
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      alignItems: 'center',
    },
    listRowLabel: { ...typographyScale.bodyMedium, fontWeight: '600', color: TOKEN.ink, marginBottom: 2 },
    listRowCaption: { ...typographyScale.caption, color: TOKEN.inkMuted },
    listRowValue: { ...typographyScale.body, color: TOKEN.ink },
    listRowValueMuted: { ...typographyScale.body, color: TOKEN.inkMuted },
    listRowValueWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flex: 1,
      minWidth: 0,
    },
    divider: { height: 1, backgroundColor: TOKEN.divider, marginLeft: PAD },
    dangerCard: {
      backgroundColor: TOKEN.surface,
      borderRadius: RADIUS.card,
      borderWidth: 1,
      borderColor: TOKEN.dangerSoft,
      ...SHADOW,
    },
    dangerLabel: { ...typographyScale.body, fontWeight: '600', color: TOKEN.danger, flex: 1 },
    profileDivider: { height: 1, backgroundColor: TOKEN.border, marginVertical: 16 },
    profileSectionLabel: { ...typographyScale.caption, fontWeight: '600', color: TOKEN.inkMuted, marginBottom: 12 },
    profileFieldRow: { marginBottom: 4 },
    profileFieldLabel: { ...typographyScale.badge, color: TOKEN.inkMuted, marginBottom: 6 },
    profileFieldValueWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 24,
    },
    profileFieldValue: { ...typographyScale.body, color: TOKEN.ink, flex: 1, marginRight: 8 },
    profileFieldValueReadOnly: { ...typographyScale.body, color: TOKEN.inkMuted },
    profileFieldValueMuted: { ...typographyScale.body, color: TOKEN.inkMuted },
    profileFieldValueDanger: { ...typographyScale.body, fontWeight: '600', color: '#DC2626' },
    profileFieldEdit: { marginTop: 8 },
    profileEditHint: { ...typographyScale.caption, color: TOKEN.inkMuted, marginBottom: 6 },
    profileEditActions: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 10 },
    profileEditActionBtn: { paddingVertical: 8, paddingHorizontal: 4 },
    profileEditActionCancel: { ...typographyScale.body, color: TOKEN.inkMuted },
    profileEditActionPrimary: {
      backgroundColor: TOKEN.accent,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: RADIUS_BUTTON,
    },
    profileEditActionPrimaryText: { ...typographyScale.button, color: '#FFF' },
    profileFieldDivider: { height: StyleSheet.hairlineWidth, backgroundColor: TOKEN.border, marginVertical: 14 },
    profileLevelDoneWrap: { paddingVertical: 12, alignItems: 'center', marginTop: 8 },
    profileLevelDoneText: { ...typographyScale.body, fontWeight: '600', color: TOKEN.accent },
    modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
    modalCenter: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      padding: PAD,
    },
    modalCard: {
      backgroundColor: TOKEN.surface,
      borderRadius: RADIUS.card,
      padding: PAD,
      width: '100%',
      maxWidth: 340,
      borderWidth: 1,
      borderColor: TOKEN.border,
    },
    modalTitle: { ...typographyScale.header, color: TOKEN.ink, marginBottom: 8 },
    modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, marginTop: 20 },
    modalActionBtn: { paddingVertical: 8, paddingHorizontal: 4 },
    editRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 4,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: TOKEN.border,
      gap: 10,
    },
    editRowPressed: { backgroundColor: 'rgba(0,0,0,0.03)' },
    editRowText: { flex: 1, ...typographyScale.bodyMedium, color: TOKEN.ink },
    signOutBtnWrap: { marginTop: 8, marginBottom: 24 },
    editSectionLabel: { ...typographyScale.bodySmall, fontWeight: '600', color: TOKEN.ink, marginBottom: 8 },
    profileEditInput: {
      backgroundColor: TOKEN.surface,
      borderWidth: 1,
      borderColor: TOKEN.border,
      borderRadius: RADIUS_BUTTON,
      paddingHorizontal: 14,
      paddingVertical: 12,
      ...typographyScale.body,
      color: TOKEN.ink,
    },
    levelOptionList: {
      marginTop: 4,
      borderRadius: RADIUS_BUTTON,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: TOKEN.border,
    },
    displayLangOptions: {
      marginTop: 4,
      borderRadius: RADIUS_BUTTON,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: TOKEN.border,
    },
    levelOptionDivider: { height: StyleSheet.hairlineWidth, backgroundColor: TOKEN.border },
    levelOptionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: PAD,
      backgroundColor: TOKEN.surface,
    },
    levelOptionRowActive: { backgroundColor: TOKEN.accentSoft },
    levelOptionText: { ...typographyScale.bodyMedium, color: TOKEN.ink },
    levelOptionCheck: { ...typographyScale.bodyMedium, fontWeight: '600', color: TOKEN.accent },
    profileDoneBtn: {
      marginTop: 20,
      paddingVertical: 14,
      borderRadius: RADIUS_BUTTON,
      backgroundColor: TOKEN.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileDoneBtnText: { ...typographyScale.button, color: '#FFF' },
    signOutBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: RADIUS.card,
      borderWidth: 1,
      borderColor: TOKEN.border,
      backgroundColor: TOKEN.surface,
    },
    signOutBtnText: { ...typographyScale.button, color: TOKEN.ink },
    backBtnText: { ...typographyScale.button, color: TOKEN.accent },
  });
}
